name: Dynamic references in workflow files for different environments in your Mule application.

on:
  push:
    branches:
      - main
      - dev
      - uat
      - qa

jobs:  # Job to call cicd-template
  call-cicd-workflow: # call cicd main flow 
    uses: uservaj/mc-cicd-org-template/.github/workflows/main.yml@main
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit
